config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#top"
  get "home/about" => "home#about", as: "about"

  resources :books, only: [:new, :index, :show, :create, :destroy, :edit, :update]do
  resource :favorites,only:[:create,:destroy]
  resources :book_comments,only:[:create,:destroy]
end
  resources :users, only: [:show, :edit, :update, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.exists?(user: user.id)
  end

  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :book_id, uniqueness: {scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, length: { minimum: 2, maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites,dependent: :destroy



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/noimages.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
  BookComment.find(params[:id]).destroy
  redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully "
      redirect_to book_path(@book)
    else
      flash[:alert]

      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment=BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to  edit_book_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if  @book.update(book_params)
       flash[:notice] = "You have update book successfully "
       redirect_to book_path
    else
        render :edit
    end
  end

  def destroy
    @books = Book.all
    @book = Book.find(params[:id])
    @book.destroy
    # unless @book.user == current_user
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
    # redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
    # redirect_to book_path(book)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <br>

  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name <%= user.name %></th>
      </tr>
      <tr>
        <th>introduction <%= user.introduction %></th>
        <th></th>
      </tr>
    </tbody>
  </table>

  <div class="info">
    <p><%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </p>
  </div>

  <h2 class="mt-3">New book</h2>
  <form action="/books" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token"
      value="5i5AhO7Im39Kp0GissjYevovKJEXnXPJrpkTVK0Hu-aG-BF00IEyNw_HwZpOT8meKA9hf4kujeWL_RRCnZWYDA" autocomplete="off">
    <div class="form-group">
      <%= form_with model: Book.new do |f| %>
      <label for="book_title">Title</label><br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label><br>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
    </div>
    <% end %>
  </form>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <br>
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <%= @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <%end %>
      </ul>
      <% end %>
      <div class="form-group">
        <%= form_with model: @book do |f| %>
        <div>
          <%= f.label :Title %><br>
          <%= f.text_field :title, autofocus: true, placeholder: "Title" %>
        </div>
        <div>
          <%= f.label :Opnion%><br>
          <%= f.text_area :body, autofocus: true, placeholder: "Body" %>
        </div>
        <div>
          <p><%= f.submit "Update Book", class:"btn btn-success" %>
          </p>
        </div>

        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'list', Book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <br>
      <h2>Books</h2>
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <%= @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%=image_tag @user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%=book.title %>
              <% end %>
            </td>
            <td>
              <%=book.body %>
            </td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "fas fa-heart heart_red" %>
              <% else %>
                <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "fas fa-heart heart_blue" %>
              <% end %>
            </td>
            <td>
              <%= "コメント数:#{book.book_comments.count}" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'list', Book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <br>
      <h2>Books</h2>
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <%= @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <%end %>
      </ul>
      <% end %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%=image_tag @user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%=book.title %>
              <% end %>
            </td>
            <td>
              <%=book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'list',  book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.id) do %>
              <%=image_tag @book.user.get_profile_image(100,100) %>
              <% end %>
              <p>
                <%= link_to user_path(@user.id) do %>
                <%= @user.name %>
                <% end %>
              </p>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
              <%= link_to @book.favorites.count, book_favorites_path(@book), method: :delete, class: "fas fa-heart heart_red" %>
              <% else %>
              <%= link_to @book.favorites.count, book_favorites_path(@book), method: :post, class: "fas fa-heart heart_blue" %>
              <% end %>
            </td>
            <% if @book.user == current_user %>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <td><%= link_to "Edit", edit_book_path, class:"btn btn-sm btn-success" %></td>
            <td>
              <%= link_to "Destroy", book_path(@book.id), class:"btn btn-sm btn-danger" ,method: :delete, "data-confirm" => "本当に消しますか？" %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover table-inverse">
        <tbody>
          <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%=image_tag book_comment.user.get_profile_image(100,100) %><br>
              <%= book_comment.user.name %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
            <td>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment), method: :delete %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= form_with model: [@book, @book_comment] do |f| %>
      <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
      <%= f.submit "送信する" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <br>
      <br>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">

<head>
  <title>Bookers2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class:"nav-link text-light p-10px"  do %>
              <i class="fas fa-home"></i>
              Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-users"></i>
              Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-book-open"></i>
              Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-sign-out-alt"></i>
              Log out
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-home"></i>
              Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-link"></i>
              About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-user-plus"></i>
              Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"nav-link text-light p-10px" do %>
              <i class="fas fa-sign-in-alt"></i>
              Log in
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <%= yield %>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

app/views/users/edit.html.erb
 <div class="container">
   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <br>
       <h2>User info</h2>
       <% if @user.errors.any? %>
       <%= @user.errors.count %>errors prohibited this book from being saved:
       <ul>
         <%= @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
       </ul>
       <% end %>
       <%= form_with model: @user do |f| %>
       <div>
         <%= f.label :Name %><br>
         <%= f.text_field :name, autofocus: true, placeholder: "Name" %>
       </div>
       <div>
         <%= f.label :Image %><br>
         <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
       </div>
       <div>
         <%= f.label :Introdaction %><br>
         <%= f.text_area :introduction, autofocus: true, placeholder: "Introduction" %>
       </div>
       <div class="form-group">
         <p><%= f.submit "Update User", class:"btn btn-secondary" do %>
           <% end %>
         </p>
       </div>
       <% end %>
     </div>
   </div>
 </div>

app/views/users/index.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">
     <%= render 'books/list', book: @book, user: @user %>
     <div class="col-md-8 offset-md-1">
       <br>
       <h3>Users</h3>
       <!--table-->
       <table class="table table-hover table-inverse">
         <thead>
           <tr>
             <th>image</th>
             <th>name</th>
             <th colspan="3"></th>
           </tr>
         </thead>
         <tbody>
           <% @users.each do |user| %>
           <tr>
             <td><%=image_tag user.get_profile_image(100,100) %></td>
             <td><%= user.name %></td>
             <td><%= link_to "Show", user_path(user.id) %></td>
           </tr>
           <% end %>
         </tbody>
       </table>
     </div>
   </div>
 </div>

app/views/users/show.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">
     <%= render 'books/list', book: @books, user: @user %>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
         <thead>
           <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
             <th colspan="3"></th>
           </tr>
         </thead>
         <tbody>
           <% @books.each do |book| %>
           <tr>
             <td>
               <%= link_to user_path(@user.id) do %>
               <%=image_tag @user.get_profile_image(100,100) %>
               <% end %>
             </td>
             <td>
               <%= link_to book_path(book.id) do %>
               <%=book.title %>
               <% end %>
             </td>
            <td>
              <%=book.body %>
            </td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "fas fa-heart heart_red" %>
              <% else %>
                <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "fas fa-heart heart_blue" %>
              <% end %>
            </td>
            <td>
              <%= "コメント数:#{book.book_comments.count}" %>
            </td>
           </tr>
           <% end %>
         </tbody>
       </table>
     </div>
   </div>
 </div>